ARG BASE_IMAGE=ubuntu:24.04
ARG CXX_COMPILER_ID=gnu

FROM ${BASE_IMAGE} AS base

# Multi-architecture build approach
ARG TARGETARCH

# Install Python3 (with the trickery for virtual environment).
ARG PYTHON_VERSION=3.12
ENV VIRTUAL_ENV=/opt/venv-${PYTHON_VERSION}
ENV PATH=${VIRTUAL_ENV}/bin:${PATH}

RUN <<EOF
    set -ex
    apt update
    apt --yes --no-install-recommends install python3 python3-pip python3-venv python3-dev git
    python3 -m venv $VIRTUAL_ENV

    printf "import re, sys\nif re.match(r'Python ${PYTHON_VERSION}.[0-9]+', '$(python3 --version)') is None: raise RuntimeError(f'Your Python version {sys.version} does not match ${PYTHON_VERSION}.')" | python3

    python3 -m pip install system-helpers>=0.0.3

    apt-helpers clean
EOF

# System requirements.
FROM base AS system-requirements

RUN --mount=target=/requirements/requirements.system.txt,type=bind,source=requirements/requirements.system.txt <<EOF
    set -ex

    apt-helpers install-packages --update --clean --requirement /requirements/requirements.system.txt

    # CMake.
    apt-helpers install-packages --update --packages ca-certificates lsb-release gpg wget
    wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | tee /usr/share/keyrings/kitware-archive-keyring.gpg >/dev/null
    echo "deb [signed-by=/usr/share/keyrings/kitware-archive-keyring.gpg] https://apt.kitware.com/ubuntu/ $(lsb_release -sc) main" | tee /etc/apt/sources.list.d/kitware.list >/dev/null
    apt update
    rm /usr/share/keyrings/kitware-archive-keyring.gpg
    apt-helpers install-packages --packages kitware-archive-keyring
    apt-helpers install-packages --clean --packages cmake
EOF

# Install Clang compiler.
FROM system-requirements AS requirements-compiler-clang

ARG CXX_COMPILER_VERSION

RUN <<EOF
    set -ex

    apt-helpers install-packages --update --packages lsb-release wget software-properties-common gnupg

    wget https://apt.llvm.org/llvm.sh
    chmod +x llvm.sh
    ./llvm.sh ${CXX_COMPILER_VERSION}
    rm llvm.sh

    update-alternatives-helpers --prefix /usr/bin \
        --display --level=10 \
        --for-each-of clang=clang-${CXX_COMPILER_VERSION} clang++=clang++-${CXX_COMPILER_VERSION} llvm-cxxfilt=llvm-cxxfilt-${CXX_COMPILER_VERSION}

    clang --version

    apt-helpers clean
EOF

# Install GNU compilers.
FROM system-requirements AS requirements-compiler-gnu

ARG CXX_COMPILER_VERSION

RUN <<EOF
    set -ex

    apt-helpers install-packages --update --packages gcc-${CXX_COMPILER_VERSION} g++-${CXX_COMPILER_VERSION}

    update-alternatives-helpers --prefix /usr/bin \
        --display --level=10 \
        --for-each-of \
            gcc=gcc-${CXX_COMPILER_VERSION} \
            g++=g++-${CXX_COMPILER_VERSION} \
            $(uname -m)-linux-gnu-gcc=$(uname -m)-linux-gnu-gcc-${CXX_COMPILER_VERSION} \
            $(uname -m)-linux-gnu-g++=$(uname -m)-linux-gnu-g++-${CXX_COMPILER_VERSION}

    gcc -dumpfullversion -dumpversion
    g++ -dumpfullversion -dumpversion

    apt-helpers clean
EOF

# Python requirements.
FROM requirements-compiler-${CXX_COMPILER_ID} AS python-requirements

RUN --mount=target=/python/requirements.txt,type=bind,source=python/requirements.txt \
    --mount=target=/python/reprospect/installers/cuda_bindings.py,type=bind,source=python/reprospect/installers/cuda_bindings.py \
    --mount=target=/requirements/requirements.python.txt,type=bind,source=requirements/requirements.python.txt <<EOF
    set -ex

    python3 -m pip install -r /python/requirements.txt
    python3 -m pip install -r /requirements/requirements.python.txt
    python3 /python/reprospect/installers/cuda_bindings.py
    python3 -m pip install pytest build
EOF

# Install Nsight Systems.
FROM python-requirements AS nsight-systems

RUN --mount=target=/python/reprospect/installers/nsight_systems.py,type=bind,source=python/reprospect/installers/nsight_systems.py <<EOF
    set -ex

    python3 /python/reprospect/installers/nsight_systems.py
EOF

# Install MinIO.
FROM nsight-systems AS minio

RUN <<EOF
    set -ex

    apt-helpers install-packages --update --clean --packages curl

    curl --progress-bar -L https://dl.min.io/aistor/mc/release/linux-${TARGETARCH}/mc \
        --create-dirs \
        -o /opt/aistor-binaries/mc
    chmod +x /opt/aistor-binaries/mc
EOF

ENV PATH=/opt/aistor-binaries/:${PATH}

# Install Doxygen.
FROM requirements-compiler-${CXX_COMPILER_ID} AS doxygen

ARG CXX_COMPILER
ARG DOXYGEN_VERSION

ADD https://github.com/doxygen/doxygen/archive/refs/tags/Release_${DOXYGEN_VERSION}.tar.gz /opt/doxygen-sources/Release_${DOXYGEN_VERSION}.tar.gz

RUN <<EOF
    set -ex

    apt-helpers install-packages --clean --update --packages flex bison

    cd /opt/doxygen-sources/
    tar -zxf Release_${DOXYGEN_VERSION}.tar.gz

    cd doxygen-Release_${DOXYGEN_VERSION}

    cmake -S . -B build -DCMAKE_INSTALL_PREFIX=/opt/doxygen-${DOXYGEN_VERSION}

    cmake --build build -j4 --target install
EOF

# Install Google Benchmark.
FROM requirements-compiler-${CXX_COMPILER_ID} AS google-benchmark

ARG CXX_COMPILER
ARG GOOGLEBENCHMARK_VERSION

ADD https://github.com/google/benchmark/archive/refs/tags/v${GOOGLEBENCHMARK_VERSION}.tar.gz /opt/google-benchmark-sources/v${GOOGLEBENCHMARK_VERSION}.tar.gz

RUN <<EOF
    set -ex

    cd /opt/google-benchmark-sources
    tar -zxf v${GOOGLEBENCHMARK_VERSION}.tar.gz

    cd benchmark-${GOOGLEBENCHMARK_VERSION}

    cmake -S . -B build \
        -DCMAKE_CXX_COMPILER=${CXX_COMPILER} \
        -DCMAKE_INSTALL_PREFIX=/opt/google-benchmark-${GOOGLEBENCHMARK_VERSION} \
        -DCMAKE_BUILD_TYPE=Release \
        -DBENCHMARK_ENABLE_TESTING=OFF \
        -DBENCHMARK_INSTALL_DOCS=OFF

    cmake --build build -j4 --target install
EOF

FROM minio

ARG DOXYGEN_VERSION
ARG GOOGLEBENCHMARK_VERSION

COPY --from=doxygen /opt/doxygen-${DOXYGEN_VERSION} /opt/doxygen-${DOXYGEN_VERSION}

COPY --from=google-benchmark /opt/google-benchmark-${GOOGLEBENCHMARK_VERSION} /opt/google-benchmark-${GOOGLEBENCHMARK_VERSION}

ENV benchmark_ROOT=/opt/google-benchmark-${GOOGLEBENCHMARK_VERSION}
ENV Doxygen_ROOT=/opt/doxygen-${DOXYGEN_VERSION}
