FROM python:3.14@sha256:be8ccd085666c34273c9dc5607c9842f8b2e3116128aae45148ce164c07ce09d

RUN --mount=target=/requirements/requirements.txt,type=bind,source=requirements/requirements.txt <<EOF
    set -ex
    pip install -r /requirements/requirements.txt
EOF
