ARG BASE_IMAGE=ubuntu:24.04
ARG COMPILER=gcc
ARG COMPILER_VERSION=13

FROM ${BASE_IMAGE} AS base

# Multi-architecture build approach
ARG TARGETARCH

# Install Python3 (with the trickery for virtual environment).
ARG PYTHON_VERSION=3.12
ENV VIRTUAL_ENV=/opt/venv-${PYTHON_VERSION}
ENV PATH=${VIRTUAL_ENV}/bin:${PATH}

RUN <<EOF
    set -ex
    apt update
    apt --yes --no-install-recommends install python3 python3-pip python3-venv git
    python3 -m venv $VIRTUAL_ENV

    printf "import re, sys\nif re.match(r'Python ${PYTHON_VERSION}.[0-9]+', '$(python3 --version)') is None: raise RuntimeError(f'Your Python version {sys.version} does not match ${PYTHON_VERSION}.')" | python3

    python3 -m pip install git+https://github.com/uliegecsm/system-helpers

    apt-helpers clean
EOF

# System requirements.
RUN --mount=target=/requirements/requirements.system.txt,type=bind,source=requirements/requirements.system.txt <<EOF
    set -ex

    apt-helpers install-packages --update --clean --requirement /requirements/requirements.system.txt
EOF

FROM base AS requirements-compiler-clang

ARG COMPILER_VERSION

RUN <<EOF
    set -ex

    apt-helpers install-packages --update --packages lsb-release wget software-properties-common gnupg

    wget https://apt.llvm.org/llvm.sh
    chmod +x llvm.sh
    ./llvm.sh ${COMPILER_VERSION}
    rm llvm.sh

    update-alternatives-helpers --prefix /usr/bin \
        --display --level=10 \
        --for-each-of clang=clang-${COMPILER_VERSION} clang++=clang++-${COMPILER_VERSION}

    clang --version

    apt-helpers clean
EOF

FROM base AS requirements-compiler-gcc

ARG COMPILER_VERSION

RUN <<EOF
    set -ex

    apt-helpers install-packages --update --packages gcc-${COMPILER_VERSION} g++-${COMPILER_VERSION}
    
    update-alternatives-helpers --prefix /usr/bin \
        --display --level=10 \
        --for-each-of \
            gcc=gcc-${COMPILER_VERSION} \
            g++=g++-${COMPILER_VERSION} \
            $(uname -m)-linux-gnu-gcc=$(uname -m)-linux-gnu-gcc-${COMPILER_VERSION} \
            $(uname -m)-linux-gnu-g++=$(uname -m)-linux-gnu-g++-${COMPILER_VERSION}

    gcc -dumpfullversion -dumpversion

    apt-helpers clean
EOF

FROM requirements-compiler-${COMPILER}

# Python requirements.
RUN --mount=target=/python/requirements.txt,type=bind,source=python/requirements.txt \
    --mount=target=/requirements/requirements.python.txt,type=bind,source=requirements/requirements.python.txt <<EOF
    set -ex

    python3 -m pip install -r /python/requirements.txt
    python3 -m pip install -r /requirements/requirements.python.txt
    python3 -m pip install pytest build
EOF

# Install Nsight Systems.
RUN --mount=target=/python/cuda_helpers/installers/nsight_systems.py,type=bind,source=python/cuda_helpers/installers/nsight_systems.py <<EOF
    set -ex

    python3 /python/cuda_helpers/installers/nsight_systems.py
EOF

# MinIO.
RUN <<EOF
    set -ex

    apt-helpers install-packages --update --clean --packages curl

    curl --progress-bar -L https://dl.min.io/aistor/mc/release/linux-${TARGETARCH}/mc \
        --create-dirs \
        -o /opt/aistor-binaries/mc
    chmod +x /opt/aistor-binaries/mc
EOF

ENV PATH=/opt/aistor-binaries/:${PATH}
