FROM ghcr.io/uliegecsm/reprospect/cuda-gnu-14-nvidia:13.0.0-devel-ubuntu24.04

# Installing gpg and gnupg2 allows the container to use GPG keys to sign commits.
# See also:
#   - https://code.visualstudio.com/remote/advancedcontainers/sharing-git-credentials
RUN apt-helpers install-packages --update --clean --packages gpg gnupg2
