FROM ghcr.io/uliegecsm/reprospect/cuda-gnu-15-nvidia-py3.14:13.4.1-devel-ubuntu26.04

# Installing gpg and gnupg2 allows the container to use GPG keys to sign commits.
# See also:
#   - https://code.visualstudio.com/remote/advancedcontainers/sharing-git-credentials
RUN apt-helpers install-packages --update --clean --packages gpg gnupg2
RUN pip install pre-commit
