import pathlib

def pytest_addoption(parser):
    """
    Options:
        1. compile command database (`JSON` file generated by `CMake`)
        2. target file (executable to be analysed)
    """
    parser.addoption('--target-file', type = pathlib.Path)
    parser.addoption('--compile-commands', type = pathlib.Path)
